### ISSUE TITLE
Warning message 

### ISSUE THREAD

**Issue by asalekin-ubiquitouslab** [hosseinshn/GradNorm#5]
UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)
This warning message comes only for the first iteration.

**Comment by nmc-eco** [comment]
It's because the difference between the shapes of G1/G2 and C1/C2.
Change the declarations of `Weightloss1` and `Weightloss2` to scalars
`
Weightloss1 = torch.tensor(1, requires_grad=True, dtype=torch.float32)
`
`
Weightloss2 = torch.tensor(1, requires_grad=True, dtype=torch.float32)
`
See more [here](https://discuss.pytorch.org/t/why-torch-tensor-scalar-tensor-should-be-used-instead-of-tensor-1/17159).
